```{r "intro"}
#| eval: false
#| echo: false
intro <- tryCatch(
    {
        description <- packageDescription("BiocBook.tidyomics")
        pkg <- description$Package
        version <- description$Version
        authors <- eval(parse(text = description$Authors))
        license <- description$License
        glue::glue(
            "**Package:** {pkg}<br/>\n", 
            "**Authors:** {paste(format(authors, include = c('given', 'family', 'role')), collapse = ', ')}<br/>\n", 
            "**Compiled:** {as.character(Sys.Date())}<br/>\n", 
            "**Package version:** {version}<br/>\n", 
            "**R version:** <b style='color:red;'>{R.version.string}</b><br/>\n", 
            "**BioC version:** <b style='color:red;'>{BiocManager::version()}</b><br/>\n", 
            "**License:** {license}<br/>"
        )
    }, 
    error = function(e) {"Local preview"}
)
```

## What is `tidyomics`? {-}

The `tidyverse` and Bioconductor ecosystems are transforming R-based 
data science and biological data analysis. **`tidyomics` bridges the gap 
between these ecosystems, enabling analysts to leverage the power of tidy 
data principles in omic analyses.**

This integration fosters cross-disciplinary 
collaborations, reduces barriers to entry for new users and enhances code 
readability, reproducibility and transparency. The tidy standard applied 
to biological software creates an extensible development ecosystem where 
independent researchers can interface with new software. 

Ultimately, the `tidyomics` ecosystem, consisting of new and publicly available R 
packages, has the potential to greatly accelerate scientific discovery. 
The mission of this collaborative, worldwide project has been described in 
more detail in [Nature Methods (2024)](https://doi.org/10.1038/s41592-024-02299-2):

> _Hutchison, William J., Timothy J. Keyes, Helena L. Crowell, Jacques Serizay, Charlotte Soneson, Eric S. Davis, Noriaki Sato, et al. 2024. “The tidyomics ecosystem: enhancing omic data analyses.” Nat. Methods 21 (July): 1166–70. (https://doi.org/10.1038/s41592-024-02299-2)._

## Core values {-}

Our Code of Conduct is available [here](https://github.com/tidyomics/.github/tree/main?tab=coc-ov-file).

The `tidyomics` organization is open to new members and contributions;
it is an effort of [many developers](https://github.com/orgs/tidyomics/people) 
in the Bioconductor community and beyond.

* See our [tidyomics open challenges](https://github.com/orgs/tidyomics/projects/1)
  project to see what we are currently working on;
* Issues tagged with 
  [good first issue](https://github.com/orgs/tidyomics/projects/1/views/1?filterQuery=good+first+issue)
  are those that developers think would be good for a new developer to
  start working on;
* Read over our [Guidelines for contributing](https://github.com/tidyomics/.github/blob/main/contributing.md);
* As with new users, for new developers please consider joining our
  Slack Channel,
  [#tidiness_in_bioc](https://slack.bioconductor.org).
  Most of the tidyomics developers are active there and we are happy
  to talk through updates, PRs, or give guidance on your development
  of a new package in this space.

# References {-}
